- name: Pull and Run Docker Image
  hosts: Azure-VM-ubuntu-20
  tasks:
#     - name: stop already running container
#       docker_container:
#         name: notesapp-backend
#         state: stopped
#     - name: remove container
#       docker_container:
#         name: notesapp-backend
#         state: absent
    - name: pull notesapp-backend image
      docker_image:
        name: prateek12307/notesapp-backend
        source: pull
    - name: run docker image
      docker_container:
        name: notesapp-backend
        image: prateek12307/notesapp-backend
        ports: "5000:5000"
